CREATE SCHEMA IF NOT EXISTS `authservdb`;

CREATE TABLE IF NOT EXISTS `authservdb`.`web_auth` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `User_ID` BIGINT UNSIGNED NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` CHAR(64) NOT NULL,
  `salt` CHAR(64) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `User_ID_UNIQUE` (`User_ID` ASC) VISIBLE);

CREATE TABLE IF NOT EXISTS `authservdb`.`user` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `last_login` TIMESTAMP NULL,
  `creation_date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`));

